/**
 * Build step: reads packages/cli/skills/ and generates src/generated/skills.ts
 * with all skill file contents as string literals.
 *
 * Run: tsx scripts/embed-skills.ts
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, relative } from 'node:path';

const SKILLS_DIR = join(import.meta.dirname, '..', 'skills');
const OUTPUT_FILE = join(import.meta.dirname, '..', 'src', 'generated', 'skills.ts');

async function walkDir(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkDir(fullPath)));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

async function main(): Promise<void> {
  const skillDirs = await readdir(SKILLS_DIR, { withFileTypes: true });
  const skills: Record<string, Record<string, string>> = {};

  for (const entry of skillDirs) {
    if (!entry.isDirectory()) continue;
    const skillName = entry.name;
    const skillDir = join(SKILLS_DIR, skillName);
    const files = await walkDir(skillDir);
    skills[skillName] = {};

    for (const filePath of files) {
      const relPath = relative(skillDir, filePath);
      const content = await readFile(filePath, 'utf-8');
      skills[skillName][relPath] = content;
    }
  }

  await mkdir(join(import.meta.dirname, '..', 'src', 'generated'), { recursive: true });

  const output = `// AUTO-GENERATED by scripts/embed-skills.ts — do not edit\nexport const SKILLS: Record<string, Record<string, string>> = ${JSON.stringify(skills, null, 2)};\n`;

  await writeFile(OUTPUT_FILE, output, 'utf-8');
  const count = Object.keys(skills).length;
  console.log(`Embedded ${count} skills into src/generated/skills.ts`);
}

main().catch((err) => {
  console.error('Failed to embed skills:', err);
  process.exit(1);
});
