/**
 * Generate the CLI command reference (every command, argument, and flag) from the
 * live Commander definitions. This is the source of `references/commands.md` in
 * every skill, so the agent-facing "manual" can never drift from the actual CLI.
 *
 * Builds its OWN program and force-loads all commands - it does NOT touch the
 * runtime lazy-load path in index.ts. The writer is invoked by
 * scripts/gen-command-ref.ts; a vitest (command-ref.test.ts) regenerates and
 * fails if any committed file is stale.
 *
 * Scope: this makes the FLAG reference authoritative. The narrative guidance and
 * worked examples in each SKILL.md stay hand-written.
 */
import { existsSync, readdirSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Command, type Argument, type Option } from 'commander';
import { LAZY_COMMANDS } from './lazy-commands.js';
import { registerGlobalOptions } from './global-options.js';

const HEADER = '<!-- DO NOT EDIT. Generated by `pnpm --filter @proxygate/cli gen:command-ref` from the CLI command definitions. Edit those, not this file. -->';
const REPO_ROOT = join(import.meta.dirname, '..', '..', '..');

async function buildFullProgram(): Promise<Command> {
  const program = new Command('proxygate');
  registerGlobalOptions(program);
  for (const c of LAZY_COMMANDS) {
    const register = await c.load();
    register(program);
  }
  return program;
}

function argToken(arg: Argument): string {
  const name = arg.name() + (arg.variadic ? '...' : '');
  return arg.required ? `<${name}>` : `[${name}]`;
}

function optionLine(opt: Option): string {
  return `- \`${opt.flags}\`${opt.description ? ` - ${opt.description}` : ''}`;
}

function renderCommand(cmd: Command, path: string[], depth: number): string[] {
  const full = [...path, cmd.name()];
  const args = cmd.registeredArguments.map(argToken).join(' ');
  const heading = `${'#'.repeat(Math.min(depth + 2, 6))} \`${['proxygate', ...full.slice(1), args].filter(Boolean).join(' ')}\``;
  const lines = [heading];
  if (cmd.description()) lines.push('', cmd.description());
  const aliases = cmd.aliases();
  if (aliases.length > 0) lines.push('', `Aliases: ${aliases.map((a) => `\`${a}\``).join(', ')}`);
  const opts = cmd.options.filter((o) => !o.hidden);
  if (opts.length > 0) lines.push('', ...opts.map(optionLine));
  lines.push('');
  for (const sub of cmd.commands) lines.push(...renderCommand(sub, full, depth + 1));
  return lines;
}

export async function generateCommandReference(): Promise<string> {
  const program = await buildFullProgram();
  const globalOpts = program.options.filter((o) => !o.hidden).map(optionLine);
  const out: string[] = [
    HEADER,
    '',
    '# Proxygate CLI Command Reference',
    '',
    'Auto-generated from the CLI definitions: every command, argument, and flag. For workflows and worked examples, see the skill guide (SKILL.md).',
    '',
    '## Global options',
    '',
    ...globalOpts,
    '',
    '## Commands',
    '',
  ];
  for (const cmd of program.commands) out.push(...renderCommand(cmd, ['proxygate'], 1));
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

/** Every references/commands.md across both skill trees (top-level public + CLI-embedded). */
export function findReferenceFiles(): string[] {
  const bases = [join(REPO_ROOT, 'skills'), join(REPO_ROOT, 'packages', 'cli', 'skills')];
  const files: string[] = [];
  for (const base of bases) {
    if (!existsSync(base)) continue;
    const standalone = join(base, 'references', 'commands.md');
    if (existsSync(standalone)) files.push(standalone);
    for (const entry of readdirSync(base, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const ref = join(base, entry.name, 'references', 'commands.md');
      if (existsSync(ref)) files.push(ref);
    }
  }
  return files.sort();
}

export async function writeCommandReference(): Promise<number> {
  const content = await generateCommandReference();
  const targets = findReferenceFiles();
  for (const file of targets) await writeFile(file, content, 'utf-8');
  return targets.length;
}
